"""
video_production/gemini_generator.py
======================================
Replaces D-ID with Google Gemini.
Since the public Gemini API does not currently have a raw video generation endpoint (Veo),
this module implements the fallback described in the architecture plan:
It uses Gemini (Imagen) to generate a high-quality presenter image (or falls back to 
a static presenter image if generation fails or is unsupported), which is then passed
down to Stage 3.2 (LipSyncEngine) to be animated with the audio.
"""

import os
import time
from dataclasses import dataclass
from typing import Dict, List, Any
from pathlib import Path

# Use the new google.genai SDK
import google.genai as genai
from google.genai import types

from data_acquisition.utils.logger import get_logger
from . import config as vc

logger = get_logger("video_production.gemini_generator")

@dataclass
class GeminiAvatarResult:
    article_id: int
    video_path: str = ""   # Will be a video path generated by Veo
    backend_used: str = "gemini_veo"
    status: str = "ok"


class GeminiVideoGenerator:
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY", "")
        if self.api_key:
            self.client = genai.Client(api_key=self.api_key)
        else:
            self.client = None
            
        self.source_image = str(vc.AVATAR_SOURCE_IMAGE)

    def run(self, items: List[Dict[str, Any]]) -> List[GeminiAvatarResult]:
        results = []
        for item in items:
            res = self._process(item)
            results.append(res)
        return results

    def _process(self, item: Dict[str, Any]) -> GeminiAvatarResult:
        article_id = item["article_id"]
        
        if not self.client:
            logger.warning(f"No GEMINI_API_KEY, falling back to static image for {article_id}")
            return GeminiAvatarResult(article_id, self.source_image, "static_fallback", "ok")

        output_path = vc.AVATAR_DIR / f"presenter_{article_id}.mp4"
        vc.AVATAR_DIR.mkdir(parents=True, exist_ok=True)
        
        if output_path.exists():
            logger.info(f"Using cached presenter video for {article_id}")
            return GeminiAvatarResult(article_id, str(output_path), "gemini_veo", "ok")

        logger.info(f"Generating dynamic presenter video via Veo for {article_id}...")
        
        try:
            import mimetypes
            # Upload the source image
            logger.info("Reading source image...")
            with open(self.source_image, "rb") as f:
                img_bytes = f.read()
            mime_type = mimetypes.guess_type(self.source_image)[0] or "image/jpeg"
            
            # Generate the video
            logger.info("Calling veo-3.1-fast-generate-preview...")
            operation = self.client.models.generate_videos(
                model="veo-3.1-fast-generate-preview",
                source=types.GenerateVideosSource(
                    image=types.Image(
                        image_bytes=img_bytes,
                        mime_type=mime_type
                    ),
                    prompt="Professional news anchor in a modern studio, looking directly at the camera, subtle natural head movements, blinking, slight body motion, broadcasting the news realistically.",
                ),
            )
            
            # Wait for generation
            while not operation.done:
                time.sleep(10)
                logger.info("Waiting for Veo video generation...")
                operation = self.client.operations.get(operation)
                
            if not operation.result or not getattr(operation.result, "generated_videos", None):
                logger.error("Veo video generation failed or returned no result.")
                return GeminiAvatarResult(article_id, self.source_image, "static_fallback", "error")
                
            video_uri = operation.result.generated_videos[0].video.uri
            
            # Download the video using the client
            logger.info(f"Downloading generated video from {video_uri}...")
            
            try:
                # In the genai SDK, the URI is often in the form of 'https://generativelanguage.../files/xyz'
                # We can extract the file ID and use client.files.get/download
                file_name = "files/" + video_uri.split('/')[-1]
                video_bytes = self.client.files.download(name=file_name)
                with open(output_path, 'wb') as f:
                    f.write(video_bytes)
                logger.info(f"Successfully saved presenter video to {output_path}")
            except Exception as e:
                logger.warning(f"client.files.download failed ({e}), falling back to requests...")
                import requests
                response = requests.get(video_uri, stream=True)
                if response.status_code == 200:
                    with open(output_path, 'wb') as f:
                        for chunk in response.iter_content(chunk_size=8192):
                            f.write(chunk)
                    logger.info(f"Successfully saved presenter video to {output_path}")
                else:
                    logger.error(f"Failed to download video, status code {response.status_code}")
                    return GeminiAvatarResult(article_id, self.source_image, "static_fallback", "error")
            
            return GeminiAvatarResult(
                article_id=article_id,
                video_path=str(output_path), 
                backend_used="gemini_veo",
                status="ok"
            )
        except Exception as e:
            logger.error(f"Gemini Veo generation failed: {e}")
            return GeminiAvatarResult(article_id, self.source_image, "static_fallback", "error")
